version: "2"
services:
  node_exporter:
    image: prom/node-exporter
#    image: quay.io/prometheus/node-exporter
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
      - /etc/localtime:/etc/localtime
  grafana:
    image: grafana/grafana:6.2.5
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana/plugins

  alert-manager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: always
    ports:
      - '9093:9093'
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lisi #设置mysql的root密码
      MYSQL_DATABASE: lisi #设置mysql数据库
      MYSQL_USER: lisi #添加授权用户
      MYSQL_PASSWORD: lisi #添加授权用户密码
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  php-fpm:
    container_name: php-fpm
    image: phpfpm:7.2-fpm
    restart: always
    ports:
      - "9000:9000"
    volumes:             # 这里路径映射要与nginx的相同，使php能读取nginx的html下的php文件
      - /var/www/html:/usr/share/nginx/html
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - /var/www/html:/usr/share/nginx/html
      - /data/logs/nginx:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf


  mysqld_exporter:
    image: prom/mysqld-exporter
    #image: bitnami/mysqld-exporter
    container_name: mysqld_exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "root:lisi@(mysql:3306)/lisi"
    ports:
      - "9104:9104"

  nginx_exporter:
    image: fish/nginx-exporter
    container_name: nginx_exporter
    command: -nginx.scrape_uri=http://139.159.185.251/nginx_status
    restart: always
    ports:
      - "9113:9113"

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/data/docker:ro
    ports:
      - "8080:8080"
